-- CreateEnum
CREATE TYPE "SetupStep" AS ENUM ('VERIFY_EMAIL', 'CHOOSE_MODE', 'CONFIGURE_RECURRING_TIERS', 'CONFIGURE_RECURRING_CHARGES', 'CONFIGURE_RECURRING_BILLING', 'REVIEW_RECURRING', 'CONNECT_STRIPE', 'CHOOSE_ACCOUNT_CODE', 'COMPLETE');

-- AlterTable
ALTER TABLE "Business" ADD COLUMN     "setupCompletedAt" TIMESTAMP(3),
ADD COLUMN     "setupStep" "SetupStep" NOT NULL DEFAULT 'VERIFY_EMAIL';
